version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      # - image: amazon/aws-cli
      - image: cimg/go:1.17
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: echo "this is the build job"
      - run: docker images
      - run: docker ps
  test:
    docker:
      - image: amazon/aws-cli
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the test job"
      - run: docker container ls


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
