version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Install Dependencies
          command: |
            amazon-linux-extras install docker -y;
      - run:
          name: Build and push image
          command: |
            export IMAGE_TAG=${CIRCLE_WORKFLOW_ID}
            echo ${AWS_DEFAULT_REGION}
            ./create-docker-env.sh
            ls
            cat docker-env
            docker build --tag ${ECR_REPOSITORY}/${APP_NAME}:${IMAGE_TAG} .
            docker images 
            docker login -u AWS -p $(aws ecr get-login-password) ${ECR_REPOSITORY}
            docker push ${ECR_REPOSITORY}/${APP_NAME}:${IMAGE_TAG}

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
